// styles.js
import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  safeArea: { flex: 1, backgroundColor: "#f9f9f9" },
  topBar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    marginTop: 4,
  },
  pickerContainer: {
    flexDirection: "row",
    alignItems: "center",
    backgroundColor: "#fff",
    paddingHorizontal: 12,
    borderWidth: 1,
    borderColor: "#e7e7e7",
    flex: 1,
    borderRadius: 10,
    height: 42,
  },
  pickerLabel: {
    fontSize: 12,
    fontWeight: "800",
    color: "#7b00af",
    marginRight: 8,
  },
  dropdownSelector: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
  },
  selectedSurahText: { fontSize: 14, color: "#018785", fontWeight: "700" },
  dropdownArrow: { fontSize: 10, color: "#2e7d32" },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.4)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    width: "85%",
    maxHeight: "70%",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
  },
  modalTitle: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#2e7d32",
    marginBottom: 16,
    textAlign: "center",
  },
  modalItem: { paddingVertical: 12, paddingHorizontal: 16, borderRadius: 8 },
  modalItemSelected: { backgroundColor: "#e8f5e9" },
  modalItemText: { fontSize: 15, color: "#333" },
  modalItemTextSelected: { color: "#2e7d32", fontWeight: "bold" },
  container: { flex: 1, paddingHorizontal: 24 },
  lightContainer: { backgroundColor: "#f9f9f9" },
  darkContainer: { backgroundColor: "#121212" },
  center: {
    flex: 1,
    justifyContent: "center",
    alignItems: "center",
    backgroundColor: "#fff",
  },
  loadingText: { marginTop: 10, fontSize: 14, color: "#666" },
  headerBadge: {
    backgroundColor: "#e8f5e9",
    borderRadius: 12,
    padding: 20,
    marginTop: 8,
    marginBottom: 10,
    alignItems: "center",
    borderWidth: 1,
    borderColor: "#c8e6c9",
  },
  headerSubtitle: {
    fontSize: 11,
    fontWeight: "800",
    color: "#2e7d32",
    letterSpacing: 2,
  },
  headerTitle: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#111",
    marginVertical: 4,
  },
  headerNumber: { fontSize: 13, color: "#666", fontWeight: "500" },
  bismillahText: {
    fontSize: 34,
    textAlign: "center",
    color: "#2e7d32",
    marginVertical: 25,
    lineHeight: 52,
  },
  pageBlock: {
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 16,
    marginVertical: 15,
    borderWidth: 1,
    borderColor: "#f0f0f0",
  },
  darkPageBlock: {
    backgroundColor: "#1e1e1e",
    borderRadius: 16,
    padding: 16,
    marginVertical: 15,
    borderWidth: 1,
    borderColor: "#2d2d2d",
  },
  ayahRowContainer: {
    marginBottom: 24,
    borderBottomWidth: 1,
    borderBottomColor: "#f7f7f7",
    paddingBottom: 16,
  },
  arabicText: {
    fontSize: 28,
    textAlign: "right",
    lineHeight: 60,
    color: "#222",
    marginBottom: 10,
  },
  darkArabicText: {
    fontSize: 28,
    textAlign: "right",
    lineHeight: 60,
    color: "#e0e0e0",
    marginBottom: 10,
  },
  verseNumberBadge: { fontSize: 18, color: "#2e7d32" },
  englishText: {
    fontSize: 15,
    color: "#000",
    textAlign: "left",
    lineHeight: 24,
  },
  darkEnglishText: {
    fontSize: 15,
    color: "#b0b0b0",
    textAlign: "left",
    lineHeight: 24,
  },
  englishNumberPrefix: { fontWeight: "bold", color: "#635968" },
  pageFooterSeparator: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    marginTop: 10,
  },
  lineDivider: {
    flex: 1,
    height: 1,
    backgroundColor: "#e0e0e0",
    marginHorizontal: 10,
  },
  pageFooterText: {
    fontSize: 11,
    color: "#999",
    fontWeight: "700",
    letterSpacing: 1.5,
  },
  settingsButton: {
    width: 40,
    height: 40,
    marginLeft: 8,
    borderRadius: 10,
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#e7e7e7",
    justifyContent: "center",
    alignItems: "center",
  },

  settingsModal: {
    width: "85%",
    maxHeight: "80%",
    backgroundColor: "#fff",
    borderRadius: 16,
    padding: 18,
  },
  sectionLabel: {
    fontSize: 13,
    fontWeight: "700",
    color: "#444",
    marginTop: 14,
    marginBottom: 6,
    textTransform: "uppercase",
    letterSpacing: 0.5,
  },
  toggleRow: {
    flexDirection: "row",
    backgroundColor: "#f0f0f0",
    borderRadius: 8,
    padding: 2,
    marginBottom: 10,
  },
  toggleBtn: {
    flex: 1,
    paddingVertical: 8,
    alignItems: "center",
    borderRadius: 6,
  },
  toggleActive: { backgroundColor: "#2e7d32" },
  toggleBtnText: { fontSize: 13, fontWeight: "600", color: "#666" },
  toggleActiveText: { color: "#fff" },
  selectionWrap: {
    flexDirection: "row",
    flexWrap: "wrap",
    gap: 6,
    marginBottom: 10,
  },
  pillOption: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#ddd",
    backgroundColor: "#fafafa",
  },
  pillOptionSelected: { backgroundColor: "#e8f5e9", borderColor: "#2e7d32" },
  pillOptionText: { fontSize: 12, color: "#555" },
  pillOptionTextSelected: { color: "#2e7d32", fontWeight: "700" },
  sizeControlRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
    marginVertical: 6,
  },
  sizeBtn: {
    backgroundColor: "#e8f5e9",
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 8,
  },
  sizeBtnText: { color: "#2e7d32", fontWeight: "bold", fontSize: 14 },
  sizeValueDisplay: { fontSize: 14, fontWeight: "600", color: "#333" },
  fontOption: {
    padding: 12,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e5e5e5",
    marginTop: 6,
  },
  fontOptionSelected: { backgroundColor: "#e8f5e9", borderColor: "#2e7d32" },
  fontOptionRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
  },
  fontLabelText: { fontSize: 14, color: "#333" },
  fontPreviewArabic: { fontSize: 18, color: "#2e7d32" },
  donationSectionBorder: {
    marginTop: 20,
    padding: 14,
    borderRadius: 12,
    backgroundColor: "#fffde7",
    borderWidth: 1,
    borderColor: "#fff59d",
    alignItems: "center",
  },
  donationHeadline: { fontSize: 14, fontWeight: "700", color: "#eda260" },
  donationSubtitle: {
    fontSize: 11,
    color: "#5d4037",
    textAlign: "center",
    marginVertical: 6,
    lineHeight: 15,
  },
  donationButtonSubmit: {
    backgroundColor: "#eda260",
    paddingHorizontal: 20,
    paddingVertical: 10,
    borderRadius: 8,
    marginTop: 4,
    width: "100%",
    alignItems: "center",
  },
  donationButtonText: { color: "#fff", fontWeight: "700", fontSize: 13 },
  footerDeveloperCredit: {
    marginTop: 30,
    alignItems: "center",
    paddingVertical: 10,
  },
  creditText: { fontSize: 13, fontWeight: "600", color: "#555" },
  creditSubtext: {
    fontSize: 11,
    color: "#999",
    fontStyle: "italic",
    marginTop: 2,
  },
  darkBg: { backgroundColor: "#121212" },
  darkBorderBg: { backgroundColor: "#1e1e1e", borderColor: "#2d2d2d" },
  selectSurahDarkText: { color: "#e9be30" },
  darkTextContent: { color: "#b0b0b0" },
  darkTextHeader: { color: "#f5f0f0" },
  darkModalContent: { backgroundColor: "#1e1e1e" },
  darkFontOption: { borderColor: "#2d2d2d" },
  darkHeaderBadge: { backgroundColor: "#1b2e1c", borderColor: "#2e7d32" },
});


export default styles;