// surahs.js
export const SURAH_LIST = [
  { id: 1, name: "Al-Fatihah", total_verses: 7 , englishNameTranslation: "The Opening", revelationType: "Meccan" },
  { id: 2, name: "Al-Baqarah", total_verses: 286, englishNameTranslation: "The Cow", revelationType: "Medinan" },
  { id: 3, name: "Ali 'Imran", total_verses: 200, englishNameTranslation: "The Family of Imran", revelationType: "Medinan" },
  { id: 4, name: "An-Nisa", total_verses: 176, englishNameTranslation: "The Women", revelationType: "Medinan" },
  { id: 5, name: "Al-Ma'idah", total_verses: 120, englishNameTranslation: "The Meat", revelationType: "Medinan" },
  { id: 6, name: "Al-An'am", total_verses: 165, englishNameTranslation: "The Cattle", revelationType: "Meccan" },
  { id: 7, name: "Al-A'raf", total_verses: 206, englishNameTranslation: "The Heights", revelationType: "Meccan" },
  { id: 8, name: "Al-Anfal", total_verses: 75, englishNameTranslation: "The Spoils of War", revelationType: "Medinan" },
  { id: 9, name: "At-Tawbah", total_verses: 129, englishNameTranslation: "The Repentance", revelationType: "Medinan" },
  { id: 10, name: "Yunus", total_verses: 109, englishNameTranslation: "Jonah", revelationType: "Meccan" },
  { id: 11, name: "Hud", total_verses: 123, englishNameTranslation: "Hud", revelationType: "Meccan" },
  { id: 12, name: "Yusuf", total_verses: 111, englishNameTranslation: "Joseph", revelationType: "Meccan" },
  { id: 13, name: "Ar-Ra'd", total_verses: 43, englishNameTranslation: "The Thunder", revelationType: "Medinan" },
  { id: 14, name: "Ibrahim", total_verses: 52, englishNameTranslation: "Abraham", revelationType: "Meccan" },
  { id: 15, name: "Al-Hijr", total_verses: 99, englishNameTranslation: "The Rocky Tract", revelationType: "Meccan" },
  { id: 16, name: "An-Nahl", total_verses: 128, englishNameTranslation: "The Bee", revelationType: "Medinan" },
  { id: 17, name: "Al-Isra", total_verses: 111, englishNameTranslation: "The Night Journey", revelationType: "Medinan" },
  { id: 18, name: "Al-Kahf", total_verses: 110, englishNameTranslation: "The Cave", revelationType: "Medinan" },
  { id: 19, name: "Maryam", total_verses: 98, englishNameTranslation: "Mary", revelationType: "Meccan" },
  { id: 20, name: "Taha", total_verses: 135, englishNameTranslation: "Ta-Ha", revelationType: "Meccan" },
  { id: 21, name: "Al-Anbiya", total_verses: 112, englishNameTranslation: "The Prophets", revelationType: "Meccan" },
  { id: 22, name: "Al-Hajj", total_verses: 78, englishNameTranslation: "The Pilgrimage", revelationType: "Medinan" },
  { id: 23, name: "Al-Mu'minun", total_verses: 118, englishNameTranslation: "The Believers", revelationType: "Medinan" },
  { id: 24, name: "An-Nur", total_verses: 64, englishNameTranslation: "The Light", revelationType: "Medinan" },
  { id: 25, name: "Al-Furqan", total_verses: 77, englishNameTranslation: "The Criterion", revelationType: "Meccan" },
  { id: 26, name: "Ash-Shu'ara", total_verses: 227, englishNameTranslation: "The Poets", revelationType: "Meccan" },
  { id: 27, name: "An-Naml", total_verses: 93, englishNameTranslation: "The Ant", revelationType: "Meccan" },
  { id: 28, name: "Al-Qasas", total_verses: 88, englishNameTranslation: "The Stories", revelationType: "Meccan" },
  { id: 29, name: "Al-'Ankabut", total_verses: 69, englishNameTranslation: "The Spider", revelationType: "Meccan" },
  { id: 30, name: "Ar-Rum", total_verses: 60, englishNameTranslation: "The Romans", revelationType: "Meccan" },
  { id: 31, name: "Luqman", total_verses: 34, englishNameTranslation: "Luqman", revelationType: "Meccan" },
  { id: 32, name: "As-Sajdah", total_verses: 30, englishNameTranslation: "The Prostration", revelationType: "Meccan" },
  { id: 33, name: "Al-Ahzab", total_verses: 73, englishNameTranslation: "The Confederates", revelationType: "Medinan" },
  { id: 34, name: "Saba", total_verses: 54, englishNameTranslation: "Sheba", revelationType: "Meccan" },
  { id: 35, name: "Fatir", total_verses: 45, englishNameTranslation: "The Creator", revelationType: "Meccan" },
  { id: 36, name: "Ya-Sin", total_verses: 83, englishNameTranslation: "Ya-Sin", revelationType: "Meccan" },
  { id: 37, name: "As-Saffat", total_verses: 182, englishNameTranslation: "The Ranks", revelationType: "Meccan" },
  { id: 38, name: "Sad", total_verses: 88, englishNameTranslation: "Sad", revelationType: "Meccan" },
  { id: 39, name: "Az-Zumar", total_verses: 75, englishNameTranslation: "The Groups", revelationType: "Meccan" },
  { id: 40, name: "Ghafir", total_verses: 85, englishNameTranslation: "The Forgiver", revelationType: "Meccan" },
  { id: 41, name: "Fussilat", total_verses: 54, englishNameTranslation: "The Expounder", revelationType: "Meccan" },
  { id: 42, name: "Ash-Shura", total_verses: 53, englishNameTranslation: "The Consultation", revelationType: "Meccan" },
  { id: 43, name: "Az-Zukhruf", total_verses: 89, englishNameTranslation: "The Ornaments of Gold", revelationType: "Meccan" },
  { id: 44, name: "Ad-Dukhan", total_verses: 59, englishNameTranslation: "The Smoke", revelationType: "Meccan" },
  { id: 45, name: "Al-Jathiyah", total_verses: 37, englishNameTranslation: "The Kneeling", revelationType: "Meccan" },
  { id: 46, name: "Al-Ahqaf", total_verses: 35, englishNameTranslation: "The Dunes", revelationType: "Meccan" },
  { id: 47, name: "Muhammad", total_verses: 38, englishNameTranslation: "Muhammad", revelationType: "Medinan" },
  { id: 48, name: "Al-Fath", total_verses: 29, englishNameTranslation: "The Victory", revelationType: "Medinan" },
  { id: 49, name: "Al-Hujurat", total_verses: 18, englishNameTranslation: "The Rooms", revelationType: "Medinan" },
  { id: 50, name: "Qaf", total_verses: 45, englishNameTranslation: "Qaf", revelationType: "Meccan" },
  { id: 51, name: "Adh-Dhariyat", total_verses: 60, englishNameTranslation: "The Winnowing Winds", revelationType: "Meccan" },
  { id: 52, name: "At-Tur", total_verses: 49, englishNameTranslation: "The Mount", revelationType: "Meccan" },
  { id: 53, name: "An-Najm", total_verses: 62, englishNameTranslation: "The Star", revelationType: "Meccan" },
  { id: 54, name: "Al-Qamar", total_verses: 55, englishNameTranslation: "The Moon", revelationType: "Meccan" },
  { id: 55, name: "Ar-Rahman", total_verses: 78, englishNameTranslation: "The Most Merciful", revelationType: "Meccan" },
  { id: 56, name: "Al-Waqi'ah", total_verses: 96, englishNameTranslation: "The Inevitable", revelationType: "Meccan" },
  { id: 57, name: "Al-Hadid", total_verses: 29, englishNameTranslation: "The Iron", revelationType: "Medinan" },
  { id: 58, name: "Al-Mujadilah", total_verses: 22, englishNameTranslation: "The Pleading Woman", revelationType: "Medinan" },
  { id: 59, name: "Al-Hashr", total_verses: 24, englishNameTranslation: "The Exile", revelationType: "Medinan" },
  { id: 60, name: "Al-Mumtahanah", total_verses: 13, englishNameTranslation: "The Woman to be Examined", revelationType: "Medinan" },
  { id: 61, name: "As-Saff", total_verses: 14, englishNameTranslation: "The Ranks", revelationType: "Medinan" },
  { id: 62, name: "Al-Jumu'ah", total_verses: 11, englishNameTranslation: "The Friday", revelationType: "Medinan" },
  { id: 63, name: "Al-Munafiqun", total_verses: 11, englishNameTranslation: "The Hypocrites", revelationType: "Medinan" },
  { id: 64, name: "At-Taghabun", total_verses: 18, englishNameTranslation: "The Mutual Loss and Gain", revelationType: "Medinan" },
  { id: 65, name: "At-Talaq", total_verses: 12, englishNameTranslation: "The Divorce", revelationType: "Medinan" },
  { id: 66, name: "At-Tahrim", total_verses: 12, englishNameTranslation: "The Prohibition", revelationType: "Medinan" },
  { id: 67, name: "Al-Mulk", total_verses: 30, englishNameTranslation: "The Kingdom", revelationType: "Meccan" },
  { id: 68, name: "Al-Qalam", total_verses: 52, englishNameTranslation: "The Pen", revelationType: "Meccan" },
  { id: 69, name: "Al-Haqqah", total_verses: 52, englishNameTranslation: "The Reality", revelationType: "Meccan" },
  { id: 70, name: "Al-Ma'arij", total_verses: 44, englishNameTranslation: "The Ascending Paths", revelationType: "Meccan" },
  { id: 71, name: "Nuh", total_verses: 28, englishNameTranslation: "Noah", revelationType: "Meccan" },
  { id: 72, name: "Al-Jinn", total_verses: 28, englishNameTranslation: "The Jinn", revelationType: "Meccan" },
  { id: 73, name: "Al-Muzzammil", total_verses: 20, englishNameTranslation: "The Enwrapped One", revelationType: "Meccan" },
  { id: 74, name: "Al-Muddaththir", total_verses: 56, englishNameTranslation: "The Cloaked One", revelationType: "Meccan" },
  { id: 75, name: "Al-Qiyamah", total_verses: 40, englishNameTranslation: "The Resurrection", revelationType: "Meccan" },
  { id: 76, name: "Al-Insan", total_verses: 31, englishNameTranslation: "The Human", revelationType: "Meccan" },
  { id: 77, name: "Al-Mursalat", total_verses: 50, englishNameTranslation: "The Emissaries", revelationType: "Meccan" },
  { id: 78, name: "An-Naba'", total_verses: 40, englishNameTranslation: "The Tidings", revelationType: "Meccan" },
  { id: 79, name: "An-Nazi'at", total_verses: 46, englishNameTranslation: "The Companions", revelationType: "Meccan" },
  { id: 80, name: "'Abasa", total_verses: 42, englishNameTranslation: "He Frowned", revelationType: "Meccan" },
  { id: 81, name: "At-Takwir", total_verses: 29, englishNameTranslation: "The Overthrowing", revelationType: "Meccan" },
  { id: 82, name: "Al-Infitar", total_verses: 19, englishNameTranslation: "The Cleaving", revelationType: "Meccan" },
  { id: 83, name: "Al-Mutaffifin", total_verses: 36, englishNameTranslation: "The Cheaters", revelationType: "Meccan" },
  { id: 84, name: "Al-Inshiqaq", total_verses: 25, englishNameTranslation: "The Splitting", revelationType: "Meccan" },
  { id: 85, name: "Al-Buruj", total_verses: 22, englishNameTranslation: "The Constellations", revelationType: "Meccan" },
  { id: 86, name: "At-Tariq", total_verses: 17, englishNameTranslation: "The Night Star", revelationType: "Meccan" },
  { id: 87, name: "Al-A'la", total_verses: 19, englishNameTranslation: "The Most High", revelationType: "Meccan" },
  { id: 88, name: "Al-Ghashiyah", total_verses: 26, englishNameTranslation: "The Overwhelming", revelationType: "Meccan" },
  { id: 89, name: "Al-Fajr", total_verses: 30, englishNameTranslation: "The Dawn", revelationType: "Meccan" },
  { id: 90, name: "Al-Balad", total_verses: 20, englishNameTranslation: "The City", revelationType: "Meccan" },
  { id: 91, name: "Ash-Shams", total_verses: 15, englishNameTranslation: "The Sun", revelationType: "Meccan" },
  { id: 92, name: "Al-Layl", total_verses: 21, englishNameTranslation: "The Night", revelationType: "Meccan" },
  { id: 93, name: "Ad-Duha", total_verses: 11, englishNameTranslation: "The Morning Hours", revelationType: "Meccan" },
  { id: 94, name: "Ash-Sharh", total_verses: 8, englishNameTranslation: "The Opening", revelationType: "Meccan" },
  { id: 95, name: "At-Tin", total_verses: 8, englishNameTranslation: "The Fig", revelationType: "Meccan" },
  { id: 96, name: "Al-'Alaq", total_verses: 19, englishNameTranslation: "The Clinging Piece", revelationType: "Meccan" },
  { id: 97, name: "Al-Qadr", total_verses: 5, englishNameTranslation: "The Power", revelationType: "Meccan" },
  { id: 98, name: "Al-Bayyinah", total_verses: 8, englishNameTranslation: "The Clear Evidence", revelationType: "Meccan" },
  { id: 99, name: "Az-Zalzalah", total_verses: 8, englishNameTranslation: "The震颤", revelationType: "Meccan" },
  { id: 100, name: "Al-'Adiyat", total_verses: 11, englishNameTranslation: "The Courser", revelationType: "Meccan" },
  { id: 101, name: "Al-Qari'ah", total_verses: 11, englishNameTranslation: "The Blast", revelationType: "Meccan" },
  { id: 102, name: "At-Takathur", total_verses: 8, englishNameTranslation: "The Rivalry", revelationType: "Meccan" },
  { id: 103, name: "Al-'Asr", total_verses: 3, englishNameTranslation: "The Time", revelationType: "Meccan" },
  { id: 104, name: "Al-Humazah", total_verses: 9, englishNameTranslation: "The Slanderer", revelationType: "Meccan" },
  { id: 105, name: "Al-Fil", total_verses: 5, englishNameTranslation: "The Elephant", revelationType: "Meccan" },
  { id: 106, name: "Quraysh", total_verses: 4, englishNameTranslation: "The Quraish", revelationType: "Meccan" },
  { id: 107, name: "Al-Ma'un", total_verses: 7, englishNameTranslation: "The Small Kindnesses", revelationType: "Meccan" },
  { id: 108, name: "Al-Kawthar", total_verses: 3, englishNameTranslation: "The Abundance", revelationType: "Meccan" },
  { id: 109, name: "Al-Kafirun", total_verses: 6, englishNameTranslation: "The Disbelievers", revelationType: "Meccan" },
  { id: 110, name: "An-Nasr", total_verses: 3, englishNameTranslation: "The Help", revelationType: "Meccan" },
  { id: 111, name: "Al-Masad", total_verses: 5, englishNameTranslation: "The Palm Fiber", revelationType: "Meccan" },
  { id: 112, name: "Al-Ikhlas", total_verses: 4, englishNameTranslation: "The Sincerity", revelationType: "Meccan" },
  { id: 113, name: "Al-Falaq", total_verses: 5, englishNameTranslation: "The Dawn", revelationType: "Meccan" },
  { id: 114, name: "An-Nas", total_verses: 6, englishNameTranslation: "The Mankind", revelationType: "Meccan" }
];